### ISSUE TITLE
Text overflow in the top bar

### ISSUE THREAD

**Issue by WodeCraft** [hovgaardgames/developertycoon#132] opened 2016-10-25 14:23 UTC
A couple of times in one session of playing Beta 5 the textbar at the top of the screen didn't seem to have the space to hold all the text (see screenshot below), but after a while the text was once again contained within the bar.

![not_enough_space_for_text](https://cloud.githubusercontent.com/assets/4112189/19689903/2deaccdc-9acf-11e6-849f-decfb17a59d8.png)

**Comment by InDieTasten** [comment] 2016-10-26 16:25
Duplicate of #103

**Closed by InDieTasten** 2016-10-26 16:25 UTC
Labels: s:duplicate
